### ISSUE TITLE
The Semantic Rule for { } VS do/end

### ISSUE THREAD

**Issue by jimweirich** [bbatsov/ruby-style-guide#162]
The style guide suggests using {...} for single line and do/end for multiple line blocks.

Is it worth mentioning the semantic rule for choosing {} VS do/end as another possibility?  The semantic rule says use {} for blocks where the primary purpose of the block is to return a value, use do/end for blocks where the primary purpose of the block is to execute side effects.

Although a minority style choice, the semantic rule does have a significant following:
- http://devblog.avdi.org/2011/07/26/the-procedurefunction-block-convention-in-ruby/
- http://talklikeaduck.denhaven2.com/2007/10/02/ruby-blocks-do-or-brace
- http://onestepback.org/index.cgi/Tech/Ruby/BraceVsDoEnd.rdoc

**Comment by zenspider** [comment]
It's been a long while, but I want to pick up Jim's torch here and run with it a bit. Namely:

> The rule could certainly be automatically enforceable via analysis of the source of the called function. 

There's probably an easy win here that can cover a majority of the cases quite easily.

and

> Style rules that only reflect what is easily discoverable by a trivial examination of the source code seem to me to be the least valuable rules.

and to push back on @bbatsov's comment:

> Generally I dislike semantic rules

So, you're planning to phase out `Style/SignalException` and `Style/NonNilCheck`? They're semantic checks, right? I agree that those are easier to intuit the semantic intent, but it is just as arguable that you can do that for the Weirich method most of the time.

I think it can also be argued that those who use the Weirich method generally don't use `do/end` on a single line. It just doesn't really mentally fit for what a `do/end` block is meant for.

**Comment by bbatsov** [comment]
I wasn't too specific - I actually like semantic rules, but I dislike enforcing them. Some rules (e.g. semantic `and` and `or`) leave some room for interpretation and are impossible to enforce consistently on a project without a human oversight. 

> So, you're planning to phase out Style/SignalException and Style/NonNilCheck? They're semantic checks, right? I agree that those are easier to intuit the semantic intent, but it is just as arguable that you can do that for the Weirich method most of the time.

They won't be phased out and I'd be happy to add support for Jim's style to RuboCop. But I'm wary of suggesting its usage in this document.

> I think it can also be argued that those who use the Weirich method generally don't use do/end on a single line. It just doesn't really mentally fit for what a do/end block is meant for.

Good point.
