### ISSUE TITLE
Slightly contradicting information on embedded expressions in strings

### ISSUE THREAD

**Issue by glacials** [bbatsov/ruby-style-guide#370]
In the [spaces-operators](https://github.com/bbatsov/ruby-style-guide#spaces-operators) section, the two options for embedded expressions in strings are clearly presented:

> As far as embedded expressions go, there are also two acceptable options:
> ```ruby
> # good - no spaces
> "string#{expr}"
> 
> # ok - arguably more readable
> "string#{ expr }"
> ```
> The first style is extremely more popular and you're generally advised to stick with it. The second, on the other hand, is (arguably) a bit more readable. As with hashes - pick one style and apply it consistently.

But in the [string-interpolation](https://github.com/bbatsov/ruby-style-guide#pad-string-interpolation) section, a line reads:

> Consider padding string interpolation code with space. It more clearly sets the code apart from the string.
> ```ruby
> "#{ user.last_name }, #{ user.first_name }"
> ```

without presenting the alternative. This second section seems more one-sided and doesn't line up with the "choose your own" recommendation from the spaces-operators section. It also seems a bit floppy for a style guide -- "consider" isn't a word that conveys any strong convention.

In addition to these two points, it's just odd that this subject is mentioned in two different places of the guide, neither with a reference to the other.

**Comment by onebree** [comment]
@glacials If you have not done so already, this weekend I will open up a pull request with an edit to the style guide.

**Comment by glacials** [comment]
I have not, go for it.

**Comment by dideler** [comment]
Can this be closed now?

**Comment by glacials** [comment]
Yes, seems fixed!
