### ISSUE TITLE
"Singleton method" should be called "class method"

### ISSUE THREAD

**Issue by rstacruz** [bbatsov/ruby-style-guide#407]
> Use `def self.method` to define singleton methods. This makes the code easier to refactor since the class name is not repeated.

the term "singleton method" is ambiguous here. It's not actually defining a method in a class that's meant to be a singleton.

Perhaps the term "class method" is more appropriate, as they're usually called in other languages.

I can't find a Ruby documentation citation on what they're called, but for reference, here's documentation from other languages:

 - PHP: class methods http://php.net/manual/en/function.get-class-methods.php
 - Python: class methods https://docs.python.org/2/library/functions.html#classmethod (though similar static methods also exist)

**Comment by philoserf** [comment]
Good catch. :+1:

**Comment by bbatsov** [comment]
> the term "singleton method" is ambiguous here. It's not actually defining a method in a class that's meant to be a singleton.

Perhaps we should change this. But keep in mind this works for any Ruby object, not just classes. A bit more details - [here](http://rubymonk.com/learning/books/4-ruby-primer-ascent/chapters/39-ruby-s-object-model/lessons/131-singleton-methods-and-metaclasses).

I'm fine with using the `class method` terminology though.

**Comment by philoserf** [comment]
I sense this is a drift in our use of language. I found the 'class method' usage more common than the 'singleton method' usage, especially in more recent sources.

**Comment by onebree** [comment]
Sorry if this seems like a stupid question... Given a class `User`, how do these methods operate differently?

```ruby
def long_name
  return "#{first_name} #{last_name} (#{extension})"
end

def self.find_by_login_or_email(login)
  find_by_name(login) || find_by_email(login)
end
```

**Comment by maicher** [comment]
There is still `singleton` remaining, few lines below (in code example):
        # have to define many singleton methods.

**Comment by diegoviola** [comment]
Se
Em 23/05/2015 06:11, "maicher" <notifications@github.com> escreveu:
