### ISSUE TITLE
Add a note about nested function declaration

### ISSUE THREAD

**Issue by ojab** [bbatsov/ruby-style-guide#437]
Unfortunately sometimes I see something like this
```ruby
def foo(x)
  def bar(y)
    do_work y
  end
  bar(x)
end
```
in the wild and it's author doesn't know that it isn't nested function declaration, but full-blown function declaration (and re-declaration on each foo() call).

I think that it won't hurt if there will be mention of this with suggestion to use lambda/Proc or "non-nested" function declaration.

**Comment by onebree** [comment]
I do not know much about definitions inside definitions... But I think any style/suggestion to prevent that from happening (if possible) would be great.

**Comment by bbatsov** [comment]
:+1: Yep, that's a good suggestion.
