### ISSUE TITLE
Recommendation for inline private, protected method

### ISSUE THREAD

**Issue by timcolonel** [bbatsov/ruby-style-guide#449]
I was wondering if there was a recommendation on the way of defining private/protected methods since ruby 2.1

```ruby
# Method 1
private

def foo

end

# Method 2
private def foo

end
```

**Comment by onebree** [comment]
How has it changed since Ruby 2.1? I am on Ruby 1.9.3 still for work. We define private methods in classes by listing `private` on its own line, then it's followed by the method definitions.

**Comment by timcolonel** [comment]
Well i am pretty sure ruby 2.1 made method definition return a symbol which can be passed to private/protected and it was not working before 
* https://bugs.ruby-lang.org/issues/3753: Feature ticket
* http://www.sitepoint.com/look-ruby-2-1/: Section 2

**Comment by onebree** [comment]
Does saying `private` only work for the immediate method definition, or for all following ones?

**Comment by timcolonel** [comment]
If you put `private` alone then all the following methods will be private but if you but the definition on the same line `private def ...` then only this method will be private.

```ruby
class Test
  def foo
    'foo'
  end

  private def bar
    'bar'
  end

  def pub
    'pub'
  end
end


t = Test.new
puts t.foo
puts t.pub
puts t.bar
```
Will print
```
foo
pub
Uncaught exception: private method `bar' called for #<Test:0x30aea38>
```

**Comment by onebree** [comment]
Okay that makes sense. Thank you very much.

**Comment by equivalent** [comment]
in contrast how about "indented" private/ protected https://github.com/bbatsov/ruby-style-guide/pull/488 ?

**Comment by bbatsov** [comment]
The community doesn't seem to have a strong position regarding this, so I'd rather not add anything to the guide at this time. Maybe a few years down the line.

**Comment by dmnd** [comment]
It's now been 18 months. Is the community ready for being able to tell when a method is private without scrolling up?

**Comment by khiav223577** [comment]
How about
```rb
# Method 3
private \
def private_method
  ...
end
```

**Comment by Enether** [comment]
@dmnd Raises a valid point. Can we not enforce our own strong position?

**Comment by eliav-lavi** [comment]
@dmnd, I feel that the inline `private` declaration encourages longer class, where the Ruby mindset would tend to prefer shorter classes where scrolling is not an issue (or is a minor issue).

**Comment by maria-lau** [comment]
@bbatsov now that it's been a few years, can we revisit this topic?

**Comment by bbatsov** [comment]
@maria-lau Sure. I wouldn't mind the creation of a new ticket or reopening this one. Ideally someone should collect some up-to-date data about the current usage `private/protected` in the wild.
