### ISSUE TITLE
Discourage Magic numbers

### ISSUE THREAD

**Issue by maasha** [bbatsov/ruby-style-guide#453]
I was wondering if one should discourage [Magic Numbers](https://en.wikipedia.org/wiki/Magic_number_(programming)):

> Unique values with unexplained meaning or multiple occurrences which could (preferably) be replaced with named constants

It might be overkill for incrementations of 1:

    count += 1

but other places it will be in order:

    DAYS_IN_WEEK = 7

    days += DAYS_IN_WEEK

**Comment by bbatsov** [comment]
This is undoubtedly a good advice, but it's not Ruby specific. We do have some generic suggestions here and there but I try to keep them to the bare minimum.

**Comment by maasha** [comment]
Right, is it a job for Rubocop?

**Comment by bbatsov** [comment]
If we can figure out a good way to detect them - sure. This won't be easy,
however.

On 17 June 2015 at 12:56, maasha <notifications@github.com> wrote:

> Right, is it a job for Rubocop?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bbatsov/ruby-style-guide/issues/453#issuecomment-112742266>
> .
>



-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by maasha** [comment]
So let's close the discussion here and start one over at Rubocop? I am sure some people will see a fun challenge in this.

**Comment by bbatsov** [comment]
Fine by me.
