### ISSUE TITLE
Parallel assignment is actually faster than sequential assignment

### ISSUE THREAD

**Issue by yous** [bbatsov/ruby-style-guide#472]
https://github.com/JuanitoFatas/fast-ruby#parallel-assignment-vs-sequential-assignment-code

> **Parallel Assignment vs Sequential Assignment [code](https://github.com/JuanitoFatas/fast-ruby/blob/master/code/general/assignment.rb)**
>
> [Read the rationale here](https://github.com/JuanitoFatas/fast-ruby/pull/50#issue-98586885).
>
> ``` sh
> $ ruby -v code/general/assignment.rb
> ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
>
> Calculating -------------------------------------
>  Parallel Assignment   149.201k i/100ms
> Sequential Assignment
>                        142.545k i/100ms
> -------------------------------------------------
>  Parallel Assignment      7.687M (± 6.9%) i/s -     38.345M
> Sequential Assignment
>                           6.320M (± 8.5%) i/s -     31.360M
>
> Comparison:
>  Parallel Assignment:  7686954.1 i/s
> Sequential Assignment:  6320425.6 i/s - 1.22x slower
> ```

**Comment by bbatsov** [comment]
The difference in performance is not significant and the resulting code is much harder to read (especially if we have more than a few variables). The style guide is mostly concerned with producing clear & readable code, performance is not a huge consideration.

**Comment by yous** [comment]
Right. But my point was:

> It is also slightly slower than separate assignment.

https://github.com/bbatsov/ruby-style-guide/blob/master/README.md#parallel-assignment

**Comment by bbatsov** [comment]
Oh, yeah. I didn't even remember this sentence. We should remove it for sure.
