### ISSUE TITLE
what to do if line is too long and params cannot be aligned?

### ISSUE THREAD

**Issue by jlerpscher** [bbatsov/ruby-style-guide#478]
Hi,

I am trying to do something good with this line:

```ruby
mail to: invitee.email, subject: I18n.t('invitation_mailer.invite_member.subject', inviter_name: inviter.identifier, team_name: @team.name)
```
My line is too long, so I have tried to rewrite it as follow:
```ruby
mail to: invitee.email, 
     subject: I18n.t('invitation_mailer.invite_member.subject',
                     inviter_name: inviter.identifier, team_name: @team.name)
```

But now, params are not aligned. What can I do?

**Comment by nbrien** [comment]
I would go for something like this
```ruby
mail to: invitee.email, 
     subject: I18n.t('invitation_mailer.invite_member.subject',
                      inviter_name: inviter.identifier, 
                      team_name: @team.name)

```

**Comment by jlerpscher** [comment]
Thank you, I already tried this way but rubocop said:

`Align the parameters of a method call if they span more than one line.`

**Comment by onebree** [comment]
Have you tried:

```ruby
mail(
  to: invitee.email, 
  subject: I18n.t(
    'invitation_mailer.invite_member.subject',
    inviter_name: inviter.identifier, 
    team_name: @team.name
  )
)
```

**Comment by jlerpscher** [comment]
Nice!! Robocop is happy! 

Many thanks @onebree !

**Comment by onebree** [comment]
@jlerpscher you are welcome! I do the same type of alignment for long hashes and arrays. And if a method takes more than one param, in most cases I use parens (like I what I did with `mail`)
