### ISSUE TITLE
How to split too long method call with one parameter?

### ISSUE THREAD

**Issue by knovoselic** [bbatsov/ruby-style-guide#492]
Let's say I have a method like this:

    def blablablablabla
      @blablablablabla ||= long_name.do_something_with even_longer_naaaaaaaaame.pluralize
    end

What would be the best way to move that one argument into the new line?
This:

    def blablablablabla
      @blablablablabla ||= long_name.do_something_with(
        even_longer_naaaaaaaaame.pluralize
      )
    end

or maybe this?

    def blablablablabla
      @blablablablabla ||= long_name.do_something_with \
        even_longer_naaaaaaaaame.pluralize
    end

or something else?

**Comment by onebree** [comment]
I would prefer the first way, using parens and dropping the method to a new line.

**Comment by knovoselic** [comment]
Me too, thanks :)

**Comment by onebree** [comment]
@knovoselic if that is what you prefer, then go with it. This style guide is merely a suggestion of the community. But always know that it is not set in stone -- companies, orgs, and even individuals have their own style guides to meet certain standards.

**Comment by knovoselic** [comment]
Actually I didn't phrase the question as I intended - I was wandering if there are any benefits if second way is used (other than it's one line shorter)? The first way looks better to me, but I was still in doubt which one I should use.

**Comment by onebree** [comment]
I prefer to avoid any `\` to denote "continue to next line". It is not as intuitive as an open brace of some sort. Also, a quick glance may make it look like you are calling a second method as itself, rather than _an argument_ to another (hence, the helpfulness of parens)
