### ISSUE TITLE
Whitespace around operators

### ISSUE THREAD

**Issue by maasha** [bbatsov/ruby-style-guide#499]
I favor aligning operators due to readability, but rubocop warns that += should be surrounded by single space - Maybe that should be at least 1 space ...

So what is the feeling on aligning operators?

https://github.com/bbatsov/ruby-style-guide#spaces-operators

```
          @status[:records_out]   += 1
          @status[:sequences_out] += 1
          @status[:residues_out]  += entry.length
```

**Comment by onebree** [comment]
Relevant blog article by @wconrad: http://wconrad.github.io/20150627/tabular-alignment-antipattern.html

**Comment by bbatsov** [comment]
That's configurable in RuboCop.
