### ISSUE TITLE
Statement regarding the use of self is very misleading, if not strictly false

### ISSUE THREAD

**Issue by adrianomitre** [bbatsov/ruby-style-guide#511]
The statement "It is only required when calling a self write accessor." in the context of [Avoid self where not required.](https://github.com/bbatsov/ruby-style-guide#no-self-unless-required) is (almost) false. There are at least one other case where `self.` is (almost) required: `self.class`.

`class` by itself is a keyword for class definition, and `self.class` invokes Kernel#class method, which returns the class of the caller. Replacing `self.class` by `class` result in a `SyntaxError: unexpected keyword_end`).

Yeah, sure, one can substitute `self.class` by `send(:class)`, but so can one replace the write accessor `self.varname = value` by `send("varname=", value)`, thus I believe the original statement is very misleading, if not strictly false. I therefore suggest rewriting the sentence as "It is only required when calling a self write accessor or Kernel#class."

**Comment by bbatsov** [comment]
Yeah, guess the wording here can be improved. Obviously the focus is on truly redundant usages of `self`.

**Comment by adrianomitre** [comment]
@bbatsov So do you agree with the wording I proposed ("It is only required when calling a self write accessor or Kernel#class.")? If so, do you intend to commit it yourself or do you prefer me to fork, commit and request a pull?

**Comment by fuadsaud** [comment]
What about `self.[]`?

**Comment by adrianomitre** [comment]
@fuadsaud In general `[]` is defined to have arguments, so such an invocation would typically generate an `ArgumentError`, but you are right, `[]`  would be taken to mean `Array.new` not `self.[]`.

**Comment by fuadsaud** [comment]
@adrianomitre yeah, I meant subscript operator with arguments. Can't use it without `self` reference.

**Comment by adrianomitre** [comment]
@fuadsaud Now I see. You indeed have a point.
```ruby
class Array
  def a; [0]; end
  def b; self.[](0); end
#  def c(n); [0] = n; end # SyntaxError
  def d(n); self.[]=(0, n); end
end

v = [1]
p v.a #=> [0]
p v.b #=> 1
v.d(2)
p v #=> [2]
```

What about the new wording be "It is only required when calling a self write accessor, `Kernel#class` or `[]` and `[]=` methods."

**Comment by fuadsaud** [comment]
:+1:

For reference: you can actually write: `self[0]` and self[0] = n`.

**Comment by adrianomitre** [comment]
:+1:

**Comment by fuadsaud** [comment]
Btw, it could be generalized to all operators: `self + other` `self > other`.

**Comment by adrianomitre** [comment]
@fuadsaud Not to all Ruby operators, but to all _overloadable_ ones, i.e., the arithmetic operators +, -, *, /, % and **, shift operators >, bitwise operators |, ^ and &, comparison operators ==, ===, >, =, and index operators [] and []=.

Suggested new wording "It is only required when calling a self write accessor, overloadable operators or Kernel#class." Shall I request a pull?

**Comment by 0x01f7** [comment]
> The statement "It is only required when calling a self write accessor." in the context of Avoid self where not required. is (almost) false. There are at least one other case where self. is (almost) required: self.class.

The sample code used in this rule may enough, I suggest remove the whole statement, or remove the word **only**.

--

> Suggested new wording "It is only required when calling a self write accessor, overloadable operators or Kernel#class."

It could be generalized to all `reversed word`, like `def`, `end`, etc. sample here(may meaningless):

```Ruby
class Foo
  def def
    puts 'in method :def'
  end
  
  def bar
    self.def
  end
end
```

**Comment by zaithottakath** [comment]
@0x01f7 Yup! `Range` has `begin` and `end` methods.
> It could be generalized to all `reversed word`, like `def`, `end`, etc.

```ruby
class MyCustomRange < Range
  def beginning_of_range
    self.begin
  end

  def end_of_range
    self.end
  end
end
```

**Comment by adrianomitre** [comment]
My final proposal: "Avoid `self` where not required. (It is only required when calling a self write accessor, methods named after reserved words, or overloadable operators.)"

Updated my [pull request](https://github.com/bbatsov/ruby-style-guide/pull/530).
