### ISSUE TITLE
Statement about the implementation of "for" seems untrue

### ISSUE THREAD

**Issue by batiste** [bbatsov/ruby-style-guide#516]
"for is implemented in terms of each (so you're adding a level of indirection), but with a twist"

I have a hard time to understand this statement. How can "for" be implemented in term of "each" when "for" is an keyword in the language and "each" is not. This doesn't really make sense.

https://github.com/ruby/ruby/blob/trunk/compile.c#L3946

Am I missing something?

**Comment by batiste** [comment]
This convinced me this is the case:

    > for x in nil do puts x end
    NoMethodError: undefined method `each' for nil:NilClass

Any reference to the Ruby source code that show how this is implemented?

**Comment by bbatsov** [comment]
No idea. I just remember reading `for` was implemented in terms of `each` in some book.

**Comment by 0x01f7** [comment]
From [Ruby Syntax](http://ruby-doc.org/docs/ruby-doc-bundle/Manual/man-1.4/syntax.html#for):

Syntax

```
for lhs... in expr [do]
  expr..
end
```

Executes body for each element in the result of expression. **for is the syntax sugar** for:

```
(expr).each `{' `|' lhs..`|' expr.. `}'
``` 

----

From RubyVM, [How to disassemble Ruby code into RubyVM opcodes/Instruction Sequences](http://rehanjaffer.com/how-to-disassemble-ruby-code-into-rubyvm-yarv-opcodes-instruction-sequences/):

```
irb(main):001:0> print RubyVM::InstructionSequence.compile('for x in nil do ; end').disasm
...
0000 trace            1                                               (   1)
0002 putnil           
0003 send             <callinfo!mid:each, argc:0, block:block in <compiled>>
0005 leave            
...
irb(main):002:0> print RubyVM::InstructionSequence.compile('nil.each do |x| end').disasm
...
```
