### ISSUE TITLE
Gemfile styling

### ISSUE THREAD

**Issue by mdkirby** [bbatsov/ruby-style-guide#520]
I would like to suggest a section for guidelines for the Gemfile, though I don't know what the conventions are or what they should be. Some questions / suggestions below:

Whitespace for version locking, use the minimal amount of whitespace needed:
```
# bad
'short-gem',                                       '~> 2.0.1'
'really-long-gem-name-that-takes-forever-to-type', '~> 1.0.0'

# good
'short-gem', '~> 2.0.1'
'really-long-gem-name-that-takes-forever-to-type', '~> 1.0.0'
```

Ordering of gems and groups:  
1. Should the non-grouped gems always be listed first, or last?
2. Should the gems in the same group be ordered alphabetically, or put related gems together?
3. Should the groups themselves be alphabetical?

**Comment by sgerrand** [comment]
> Ordering of gems and groups:
>
> 1. Should the non-grouped gems always be listed first, or last?
> 2. Should the gems in the same group be ordered alphabetically, or put
related gems together?
> 3. Should the groups themselves be alphabetical?

👍 for alphabetical ordering of gems. I don't have an opinion on sorting
groups.

**Comment by paudam** [comment]
This article pretty much covers it http://mcdowall.info/posts/gemfile-best-practices-and-discourse/
Although I personally do not like point 4 regarding the comments.

**Comment by mdkirby** [comment]
That article is pretty good, thought it sounds like point 4 (and maybe some others) will either require some discussion, or perhaps make it an option A and B, and just make sure it is consistent.

**Comment by 0x01f7** [comment]
Gemfile is a normal Ruby file, though it supports Bundler DSL. However Bundler is not a built-in part of Ruby, I don't think it's a good idea to add such a section.

> Whitespace for version locking, use the minimal amount of whitespace needed

Just run `rubocop Gemfile`, it can detect extra spaces.

> Ordering of gems and groups

Read [the Bundler section in rails-style-guide](https://github.com/bbatsov/rails-style-guide#bundler).

**Comment by jdickey** [comment]
Agreed with @0x01f7 (and @paudam). If we _do_ add Gemfile styling guidelines, doesn't his Rule 4 (comments on same line as gem) violate existing guidelines not to do that in general? Also, whatever standard we pick, I strongly doubt that any three generators (say Rails, Lotus, and Volt) would produce compliant Gemfiles by default, and at least one of them would be unlikely to be persuaded to change.

Fix what we've got, first. :grinning:

**Comment by mdkirby** [comment]
@0x01f7 - That section on bundler in the rails style guide is what originally prompted my suggestion. (see original issue here: https://github.com/bbatsov/rails-style-guide/issues/166).

Since the Gemfile isn't rails specific, it was suggested that any guidelines be put in the ruby style guide, which made sense to me, but @0x01f7 and @jdickey make a good point also. This puts the Gemfile style guide in a bit of limbo. Pragmatically, I think the rails style guide may be the best place for any Gemfile guidelines, but I would certainly defer that kind of decision to bbatsov.

The section on bundler in the rails guide mentions placing gems in specific `testing` and `development` groups, as well as OS-specific groups, but it makes no mention of the ordering of the groups or the ordering of the gems themselves. IMHO, the article that @paudam referenced looks like an excellent starting point.

As far as the extra white-space goes, rubocop is a great tool, and we have used it (especially when inheriting projects), but there are places in the style guide (https://github.com/bbatsov/ruby-style-guide#source-code-layout) that specifically set the standard for the number of spaces to use, why not also specify this for the Gemfile (if a section is added)?

**Comment by onebree** [comment]
IMO, I do not think we should add guidelines for Gemfiles. As @jdickey said, Rails would not produce compliant gemfiles (based on proposed guidelines). I see Gemfiles as a type of documentation, and like documentation, everyone has their own style to it.

Also, some of the proposed guidelines are already present in the style guide. Sticking to one type of quotation mark (double _or_ single), comments on their own line, and (as @0x01f7 pointed out with RuboCop) avoiding extra whitespace alignment.

**Comment by bbatsov** [comment]
I agree - let's not add bundler-specific info to the style guide.
