### ISSUE TITLE
Style suggestion: Do not allow constant definition below private modifier

### ISSUE THREAD

**Issue by RST-J** [bbatsov/ruby-style-guide#536]
I recently found out that Ruby classes cannot have private constants which is counterintuitive to me.
If I have a class definition like this, unless of course I know about `private` only making following method declarations private, I'd rather consider the constant also private:
```ruby
class Question
  private

  ANSWER = 42
end
```

So, I'd suggest to declare it bad style if constants are defined below a private or protected modifier. What do you think?

**Comment by 0x01f7** [comment]
Just follow [consistent-classes](https://github.com/bbatsov/ruby-style-guide#consistent-classes) style.

**Comment by pvdb** [comment]
@RST-J, you wrote:
>  I recently found out that Ruby classes cannot have private constants

You're wrong, I'm afraid... [`Module#private_constant`](https://ruby-doc.org/core-2.3.1/Module.html#method-i-private_constant) is your friend!

**Comment by RST-J** [comment]
Oh, nice, thanks @pvdb I didn't knew about that one. But I like it, because up to now I thought I just have to live with constants being always public.

**Comment by AlexWayfer** [comment]
Should be private (inner) constants near private methods (under `private`)? I think this approach is more intuitive than private constants mixed with public constants at the top of class.
