### ISSUE TITLE
Guide to pdf

### ISSUE THREAD

**Issue by lebogan** [bbatsov/ruby-style-guide#547]
You suggest using 'transmute' as a tool for generating a pdf version of this guide. I'm using Ruby 2.3.0 and I found that transmute wouldn't install due to a dependency on outdated nokogiri version 1.5.11. I cloned the repo, updated the gemspec to version 1.6, and got it to work. I'm leaving an issue request on the transmute repo.

It looks like transmute hasn't been touched for quite a while despite it being an excellant tool. Do you have any other recommendations for a converter?

Thanks for this guide. It and Rubocop are keeping my coding in line.

Lewis

**Comment by bbatsov** [comment]
I'm guessing there are non-Ruby tools that can get the job done as well. It's a pity transmuter was abandoned - the project was actually created so people can convert the style guide to html and pdf. :-)

**Comment by lebogan** [comment]
Thanks. I'll keep searching for something comparable. I am closing this issue.
