### ISSUE TITLE
validates vs validates..._of ...

### ISSUE THREAD

**Issue by mathiasuhl** [bbatsov/ruby-style-guide#571]
Hi, who did decide that validates with params is better then ie. validates_presence_of and why? I think its less readable and more complex to comprehend.

**Comment by WaKeMaTTa** [comment]
Because is more readable. Example:

```ruby
validate :tag, presence: true, in: %w(best done wonderful)
```

**Comment by bbatsov** [comment]
In general Rails-related tickets should be filed for the Rails style guide https://github.com/bbatsov/rails-style-guide
