### ISSUE TITLE
Array way

### ISSUE THREAD

**Issue by WaKeMaTTa** [bbatsov/ruby-style-guide#572]
Hello,

which is the difference between:

``` ruby
a = *(1..3)
# => [1, 2, 3]
```

and this:

``` ruby
a = (1..3).to_a
# => [1, 2, 3]
```

---

And which is accepted? And there is another way more readable?

**Comment by kevinfalting** [comment]
This is a good question and one that I've wondered about myself. I asked some of the rubyists I know and they opted for:
```ruby
a = (1..3).to_a
```
for readability reasons.

Also `.to_a` is a faster operation.

So, `.to_a` is faster and more explicit.

**Comment by bbatsov** [comment]
Indeed. I'd definitely go for `.to_a` over using the splat operator in this situation. Always optimize for readability!
