### ISSUE TITLE
Omit braces around implicit options hash

### ISSUE THREAD

**Issue by gnapse** [bbatsov/ruby-style-guide#573]
I wanted to ask a question about [this rule](https://github.com/bbatsov/ruby-style-guide#no-braces-opts-hash). It states that braces around an implicit options hash can be omitted.

```ruby
# bad
user.set({ name: 'John', age: 45, permissions: { read: true } })

# good
user.set(name: 'John', age: 45, permissions: { read: true })
```

It is hardly questioned among ruby developers that braces in this case should be omitted. But the example shown in the style guide is a one-liner. I wanted to know if every one thinks the rule also holds for a multi-line hash.

```ruby
user.set({                                    user.set(
  name: 'John',                                 name: 'John',
  age: 45,                          vs.         age: 45,
  permissions: { read: true }                   permissions: { read: true }
})                                            )
```

I personally prefer the one on the left, but I'm not sure if the rule as it is expressed in this guide, makes my preference not generally acceptable.

**Comment by WaKeMaTTa** [comment]
Check the 4th in this rule https://github.com/bbatsov/ruby-style-guide#no-double-indent
