### ISSUE TITLE
Never construct raw HTML and use Rails helpers if necessary

### ISSUE THREAD

**Issue by stephwag** [bbatsov/ruby-style-guide#594]
I noticed that you construct raw HTML in your example here https://github.com/bbatsov/ruby-style-guide#concat-strings

I think you should use a different example and add a section about constructing HTML. In the section, it should explain that you must construct HTML, use helpers such as `content_tag` and avoid writing strings of raw HTML. Not only does this save a bit of time for the programmer, but it also doesn't encourage the use of `html_safe`, which can create an XSS vulnerability if they happen to wrap the html around unclean data.

**Comment by noahpryor** [comment]
Rails style guide may be a better place for this

https://github.com/bbatsov/rails-style-guide#no-complex-view-formatting

**Comment by stephwag** [comment]
@noahpryor Oh yeah that makes more sense. I'll go put that there.

**Comment by stephwag** [comment]
Closing on behalf of https://github.com/bbatsov/rails-style-guide/issues/198
