### ISSUE TITLE
Law of Demeter

### ISSUE THREAD

**Issue by Sathors** [bbatsov/ruby-style-guide#614]
Hi,

don't you think it would be interesting to add a point about the Law of Demeter?

In Rubocop, I have found the issue bbatsov/rubocop#720, which says that this rule will not be possibly checked.
I think they were right in the issue, but still it would be nice to have something about the Law of Demeter in the style guide.

**Comment by bbatsov** [comment]
That's not something Ruby-specific, so I'd rather no include it.

**Comment by Sathors** [comment]
Hum, yeah you're right.

It would have been nice to have a cop for it, but indeed it has nothing to do with the ruby style guide.
