### ISSUE TITLE
Discouraging use of class variables in subclasses

### ISSUE THREAD

**Issue by dannyradden** [bbatsov/ruby-style-guide#624]
Why is RuboCop discouraging use of class variables in subclasses?

In the example given in the Readme.txt, it says you should use instance variables instead of class variables, however if they are changed to instance variables then the code no longer outputs 'child' as `intended.

Here is the example code in the Readme.txt:
```ruby
class Parent
  @@class_var = 'parent'

  def self.print_class_var
    puts @@class_var
  end
end

class Child < Parent
  @@class_var = 'child'
end

Parent.print_class_var # => will print 'child'
```

**Comment by Drenmi** [comment]
The example is not showing what is desired, it is showing what is so dangerous about class variables.

Why would `Parent` say it's a child, and looking **only** at the `Parent` class file, how do you explain that behaviour? You define a class variable and when you print it, the result is something completely different. The causal relationship is entirely obscured.

This leads to bugs that are hard to debug and reason about. 😀

**Comment by byronmejia** [comment]
If you need to change something of the parent, why not use functions?

```ruby
class Parent
  def speak
    puts 'Hello'
  end
end

class Child < Parent
  def speak
    puts 'Hey Fam'
  end
end
```

Very bad example, but sometimes, you want the functions to do something different rather than the variables directly being edited. Does this make sense? 😸

**Comment by dannyradden** [comment]
Aw, I completely missed the point of the example. Thanks for the explanation!
