### ISSUE TITLE
Add note about nested modules declaration

### ISSUE THREAD

**Issue by jomei** [bbatsov/ruby-style-guide#637]
I don't find any rules for nested modules declaration, such as
```
module Foo
  module Bar
    module Baz
      # some code
    end
  end
end
```
or
```
module Foo::Bar::Baz
  # some code
end

```

**Comment by 0x01f7** [comment]
a closed PR here: [Add the namespace definition guide](https://github.com/bbatsov/ruby-style-guide/pull/500).
