### ISSUE TITLE
naming of methods

### ISSUE THREAD

**Issue by BKSpurgeon** [bbatsov/ruby-style-guide#643]
estimable colleagues

thank you for this wonderful resource.

I note that in the examples given here: https://github.com/bbatsov/ruby-style-guide#snake-case-symbols-methods-vars

there is no clear mention what what is good or bad.

![image](https://cloud.githubusercontent.com/assets/15097447/23900513/bdc77646-090d-11e7-87bf-fdf49a4e380a.png)

**Comment by BKSpurgeon** [comment]
In fact i'll make a pull request with what i think should be correct and if that's good for you please accept.

**Comment by charger** [comment]
Here is comments "bad" and "good"
![6518bd281c](https://cloud.githubusercontent.com/assets/677611/23900858/7278c77a-08c3-11e7-974a-22b31a43b5c0.png)
Aren't they clear?

**Comment by BKSpurgeon** [comment]
excellent thank you! ......changes incorporated in a pull request :)
