### ISSUE TITLE
Rationale for soft tabs?

### ISSUE THREAD

**Issue by martinvelez** [bbatsov/ruby-style-guide#687]
What is the rationale for preferring soft tabs over hard tabs?  I am not proposing a change just genuinely curious why this convention was adopted.

When I edit files, I indent with tabs.  Do the majority of people indent by pressing the space bar?  I could edit my vim settings to expand tabs into 2 spaces.  However, this would affect me when I write Makefiles or Python or just want to insert actual tabs.

I have been writing Ruby for many years and only recently became interested in Rubocop.  That is where I learned about this guide.  

A relevant StackOverflow question: [https://stackoverflow.com/questions/24045822/rubocop-for-tabs](https://stackoverflow.com/questions/24045822/rubocop-for-tabs).

**Comment by cremno** [comment]
[The rationale according to matz:](http://blade.nagaokaut.ac.jp/cgi-bin/vframe.rb/ruby/ruby-talk/225040?224793-226498+split-mode-vertical)

>The real reason of 2 space indentation is that it is smallest
>distinguishable indentation.  1 space is too small for eyes.

Btw. check out the pie charts on https://ukupat.github.io/tabs-or-spaces/, especially the Ruby one.

**Comment by martinvelez** [comment]
@mikegee, thank you for the info about filetype-specific vim options.  I may go down that route.

@cremno, thank you for the two links.  The first link satisfies my curiosity.  The second link tells me that Soft tabs (spaces) are far more popular I would have ever imagined.

Personally, there are several reasons why I would prefer hard tabs.

1. Hard tabs are the default in most editors.  There is no need for special configuration.
2. The tab width can be configured to user's taste.  I have seen tastes range between 2 and 8 spaces.
3. Absent configuration, more keystrokes are required, to insert and to delete.
4. Absent configuration, consistent insertion of exactly 2 spaces might be difficult to achieve.

Thank you for your answers.
