### ISSUE TITLE
User.all.length call

### ISSUE THREAD

**Issue by zhisme** [bbatsov/ruby-style-guide#718]
Hey there. 
Can someone told me, why this is not marked as extremely bad?
Is there any real reason to load all users into memory?
I can't even imagine. It would be nice if you show me real-case usage of this example.

```
# good - if you really need to load all users into memory
User.all.length
```
[length method](https://github.com/bbatsov/rails-style-guide#size-over-count-or-length)

**Comment by tim-teufel** [comment]
This issue should go to the [Rails Style Guide](https://github.com/bbatsov/rails-style-guide), not Ruby Style Guide.
Maybe, it's even better to comment directly at https://github.com/bbatsov/rails-style-guide/pull/224.

**Comment by zhisme** [comment]
@tim-teufel Yeah, you are right, thanks!
